# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'ESColorDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ESColor', :git => 'https://github.com/KKLater/ESColor.git', :branch => 'dev'

end
